baseURL = "http://example.org/"
languageCode = "en-us"
title = "Fur"
googleAnalytics = ""
enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

[params]
snipcart_key = "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"

[params.author]
name = "fur"
email = "fur@example.com"
twitter = "fur" # twitter username without the @ symbol
phone = "+1 23456789"

[params.social]
name = "Fur Template"
links = [
	"https://github.com/CloudCannon/fur-hugo-template"
]

[_select_data]
garment_type = ["hat", "top"]

[cloudcannon._options.type]
hidden = true

[cloudcannon._comments]
map = "Update the map location and display settings."
latitude = "Coordinates for the center marker on the map."
longitude = "Coordinates for the center marker on the map."
zoom = "The zoom level for the map."
pricing_table = "Update the information in the pricing tables."
highlight = "Emphasis the text"
color = "The background color used in the plan name and call to action."
new_window = "Open link in new window"
description = "This is used for facebook shares of the page and google indexing"

[cloudcannon.collections.products]
_enabled_editors = ["data"]
_icon = "shopping_cart"